### ISSUE TITLE
Why  the minimum number of nodes  is two when using the qctl tool to create a network?

### ISSUE THREAD

**Issue by shx861** [ConsenSys/qubernetes#99]
When I use the qctl tool to initialize the network, I set the number of nodes to 1, but no k8s deployment resources are generated; after checking the code, it seems that the template  file of ‘’quorum-shared-config.yaml.erb‘’  does not support it. Why is it designed like this?

**Comment by libby** [comment]
Hello @shx861 there is no real reason for not supporting a single node network. Would you be up to modify https://github.com/ConsenSys/qubernetes/blob/master/templates/k8s/quorum-shared-config.yaml.erb#L58 to use the tm.pub key for node1 instead of node2? This would be great first issue.

**Comment by libby** [comment]
@shx861 I didn't hear back from you, so made the change: https://github.com/ConsenSys/qubernetes/commit/a47da88f5c3fcacd445e32720fe5669cdbff2fc2

You can now generate and deploy single node networks, e.x with [qct](https://github.com/ConsenSys/qubernetes/tree/master/qctl):
```
> qctl init --num 1
> qctl generate network --create
> qctl deploy network --wait
```
